### ISSUE TITLE
After %x command rest of file is super indented

### ISSUE THREAD

**Issue by JKGisMe** [CraigWilliams/BeautifyRuby#87]
After I use a terminal command the entire rest of the file is super indented. Maybe related to #47 ?

Any ideas how I could fix this even locally so I can keep using BeautifyRuby ?

``` ruby
class MyClass
  def call_python
      argument = my_value
      if(my_boolean)
        py_size = %x(cd my-folder; python myPythonScript.py #{argument} )

                            print "\n#{py_size}\n"
                            print "\nanother string\n"
                            end
                            end

                            def test_something
                              some_var = some_value
                            end
                            # .
                            # .
                            # .
                            # whole rest of the file
                            end # end of class
```

**Comment by zelig** [comment]
a quick and dirty fix is to use angle brackets after `%x`

```
%x[cd my-folder; python myPythonScript.py #{argument} ]
```

but actually why not fix it in https://github.com/CraigWilliams/BeautifyRuby/tree/master/lib/rbeautify

**Comment by zerocool4u2** [comment]
is a tricky one, according to this site: http://teohm.com/blog/2012/10/15/start-using-ruby-percent-notation/ it could be any non alphanumeric character, currently is matching only '[' and ']' in the correct format, but for what i understand of the implementation, the start and the end of a string are matched in separated regexs and also separated functions, so you could match any non alphanumeric characters instead of brackets, but you would get false positives like %w[whatever)
On the other hand you could add more matchers for the common cases "[ { (" and leave it there or.. add an extra matcher that work for all non alphanumeric excluding the common ones, in this way you would get less errors i think.

 I didn't dig that much on the code, but maybe you could add more logic to block_matcher.rb, accept all alphanumeric in ruby.rb, and check the pairs if name == :percent  (matcher name added for this), they should be kinda easy i suppose, just the bracket cases and the other ones match with each other been the same no?.

If anyone  wanna go with this, i would check if the last option is possible, it would be the cleanest one in my opinion, regards!

**Comment by levequej** [comment]
+1 on this one
